version: "3.9"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_server
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - "${MONGODB_DOCKER_PORT}:27017"
    volumes:
      - ./data:/data/db

  books:
    build: ./book-service
    container_name: book-service
    ports:
      - "${BOOK_SERVICE_PORT}:3000"
    env_file: ./.env
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
      - JWT_SECRET=$JWT_SECRET
      - PORT=$BOOK_SERVICE_PORT
    volumes:
      - /app/node_modules
    depends_on:
      - auth
      - mongodb

  clients:
    build: client-service
    container_name: client-service
    ports:
      - "${CLIENT_SERVICE_PORT}:3000"
    env_file: ./.env
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
      - JWT_SECRET=$JWT_SECRET
      - PORT=$CLIENT_SERVICE_PORT
    volumes:
      - /app/node_modules
    depends_on:
      - auth
      - books
      - mongodb

  loans:
    build: loan-service
    container_name: loan-service
    ports:
      - "${LOAN_SERVICE_PORT}:3000"
    env_file: ./.env
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
      - JWT_SECRET=$JWT_SECRET
      - PORT=$LOAN_SERVICE_PORT
    volumes:
      - /app/node_modules
    depends_on:
      - auth
      - books
      - mongodb
      - clients

  auth:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "${AUTH_SERVICE_PORT}:3000"
    env_file: ./.env
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
      - JWT_SECRET=$JWT_SECRET
      - PORT=$AUTH_SERVICE_PORT
    volumes:
      - /app/node_modules
    depends_on:
      - mongodb

volumes:
  mydata: